#!/usr/bin/env python3
"""
improvement-engine.py — Turns snapshot data into specific agent task recommendations.
Reads:  weekly-snapshots/YYYY-MM-DD.json  (latest or specified)
Writes: improvement-queue.md
"""

import os
import json
import glob
import datetime

SNAPSHOT_DIR  = os.path.join(os.path.dirname(__file__), "weekly-snapshots")
QUEUE_FILE    = os.path.join(os.path.dirname(__file__), "improvement-queue.md")
HISTORY_FILE  = os.path.join(os.path.dirname(__file__), "improvement-history.json")


# ─── Load snapshot ────────────────────────────────────────────────────────────

def load_latest_snapshot():
    files = sorted(glob.glob(os.path.join(SNAPSHOT_DIR, "*.json")))
    if not files:
        raise FileNotFoundError("No snapshots found. Run feedback-tracker.py first.")
    with open(files[-1]) as f:
        return json.load(f), files[-1]


def load_prev_snapshot():
    """Load the second-most-recent snapshot for before/after comparison."""
    files = sorted(glob.glob(os.path.join(SNAPSHOT_DIR, "*.json")))
    if len(files) < 2:
        return None
    with open(files[-2]) as f:
        return json.load(f)


# ─── Analysis helpers ─────────────────────────────────────────────────────────

class ImprovementQueue:
    def __init__(self):
        self.tasks = []

    def add(self, agent, priority, task_text=None, task=None, metric=None, data=None):
        # Accept either task_text= or task= as the task description
        text = task_text or task or ""
        self.tasks.append({
            "agent":     agent,     # SCRIBE / QUILL / PIXEL / SPARK / GENERAL
            "priority":  priority,  # HIGH / MEDIUM / LOW
            "task":      text,
            "metric":    metric,
            "data":      data,
            "created":   datetime.date.today().isoformat(),
            "status":    "PENDING",
        })

    def to_markdown(self, snapshot_date, prev=None):
        lines = [
            f"# Improvement Queue — Generated {datetime.date.today().isoformat()}",
            f"> Based on snapshot: {snapshot_date}",
            "",
            "_This file is auto-generated by improvement-engine.py. Edit with care._",
            "",
        ]

        if not self.tasks:
            lines += [
                "## ✅ No improvements needed this week",
                "",
                "All metrics within healthy ranges. Keep monitoring.",
                "",
            ]
            return "\n".join(lines)

        # Group by agent
        agents = ["SCRIBE", "QUILL", "PIXEL", "SPARK", "GENERAL"]
        by_agent = {a: [] for a in agents}
        for task in self.tasks:
            bucket = task["agent"] if task["agent"] in agents else "GENERAL"
            by_agent[bucket].append(task)

        priority_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}
        agent_emoji = {
            "SCRIBE":  "🎙️",
            "QUILL":   "✉️",
            "PIXEL":   "🎨",
            "SPARK":   "⚡",
            "GENERAL": "🔧",
        }

        total = len(self.tasks)
        high  = sum(1 for t in self.tasks if t["priority"] == "HIGH")
        med   = sum(1 for t in self.tasks if t["priority"] == "MEDIUM")
        lines += [
            f"## Summary: {total} tasks queued ({high} high priority, {med} medium)",
            "",
        ]

        # Before/after comparison block
        if prev:
            lines += ["## 📈 Before / After (vs last snapshot)", ""]
            prev_stripe = prev.get("stripe", {})
            curr_stripe = {} # filled below when we reach stripe section
            lines += ["> _(see individual sections for comparisons)_", ""]

        for agent in agents:
            tasks = by_agent[agent]
            if not tasks:
                continue
            lines += [
                f"---",
                f"## {agent_emoji.get(agent, '📌')} {agent} TASKS ({len(tasks)})",
                "",
            ]
            for t in sorted(tasks, key=lambda x: ["HIGH","MEDIUM","LOW"].index(x["priority"])):
                emoji = priority_emoji.get(t["priority"], "⚪")
                lines += [
                    f"### {emoji} [{t['priority']}] {t['task'][:80]}",
                    "",
                    f"**Full task:**",
                    f"> {t['task']}",
                    "",
                ]
                if t.get("metric"):
                    lines.append(f"**Metric:** `{t['metric']}`")
                    lines.append("")
                if t.get("data"):
                    lines.append(f"**Data:**")
                    lines.append("```json")
                    lines.append(json.dumps(t["data"], indent=2)[:500])
                    lines.append("```")
                    lines.append("")
                lines += [
                    f"- [ ] **Status:** PENDING",
                    f"- [ ] **Date queued:** {t['created']}",
                    "",
                ]

        lines += [
            "---",
            "",
            "## How to action these",
            "",
            "- **SCRIBE tasks** → Copy task into Scribe's next session. Scripts need human QA before deploying.",
            "- **QUILL tasks** → auto-apply.py can handle subject line swaps automatically.",
            "- **PIXEL tasks** → Review with Pixel, update landing page copy/layout.",
            "- **SPARK tasks** → Trigger Spark to run the recommended campaign.",
            "- **GENERAL tasks** → Route to the right agent or handle manually.",
            "",
            "_Run `python3 auto-apply.py` to automatically apply low-risk improvements (email subject lines, etc.)_",
        ]

        return "\n".join(lines)


# ─── Vapi / Call Analysis ─────────────────────────────────────────────────────

def analyze_vapi(data, q: ImprovementQueue, prev=None):
    vapi = data.get("vapi", {})
    if vapi.get("status") != "live":
        return  # no data yet

    hangup_rate   = vapi.get("hangup_rate_pct", 0)
    interest_rate = vapi.get("interest_rate_pct", 0)
    total         = vapi.get("total_calls", 0)
    warm_rate     = vapi.get("warm_rate_pct", 0)

    if total < 10:
        return  # not enough data to draw conclusions

    # Hook quality
    if hangup_rate > 30:
        q.add(
            agent    = "SCRIBE",
            priority = "HIGH",
            task     = (
                f"SCRIBE TASK: Rewrite Alex's opener — {hangup_rate:.0f}% of calls hang up in first 30s. "
                f"Current hook isn't landing. "
                f"Suggested fix: Lead with a specific local pain point ('Hey, this is Alex — I help "
                f"[business type] in [city] get more 5-star reviews without chasing people down. "
                f"Quick 45-second question?'). A/B test 3 variants next week."
            ),
            metric   = f"hangup_rate={hangup_rate}% (threshold: 30%)",
            data     = {"hangup_rate": hangup_rate, "total_calls": total,
                        "flagged_short": vapi.get("flagged_short", [])[:5]}
        )

    # Close sequence
    if interest_rate < 5 and total >= 20:
        q.add(
            agent    = "SCRIBE",
            priority = "HIGH",
            task     = (
                f"SCRIBE TASK: Close sequence needs work — only {interest_rate:.1f}% of calls result in "
                f"expressed interest (target: >10%). "
                f"Suggested fix: Add a soft close at 2-minute mark: 'It sounds like reviews are a "
                f"real issue for you — would a quick 10-min demo this week be useful?' "
                f"Log objection patterns from warm calls below."
            ),
            metric   = f"interest_rate={interest_rate}% (threshold: 5%)",
            data     = {"interest_rate": interest_rate, "warm_calls": vapi.get("flagged_warm", [])[:5]}
        )

    # Warm calls — study them
    if len(vapi.get("flagged_warm", [])) >= 3 and warm_rate > 15:
        q.add(
            agent    = "SCRIBE",
            priority = "MEDIUM",
            task     = (
                f"SCRIBE TASK: Mine warm calls for winning patterns — {warm_rate:.0f}% of calls last "
                f"3+ minutes ({vapi.get('warm_calls')} total). Review transcripts below and identify: "
                f"what did the caller say that kept them talking? Extract 2-3 phrases to inject into "
                f"the standard script."
            ),
            metric   = f"warm_rate={warm_rate}%",
            data     = {"warm_calls": vapi.get("flagged_warm", [])[:10]}
        )

    # Before/after comparison
    if prev and prev.get("vapi", {}).get("status") == "live":
        prev_hangup = prev["vapi"].get("hangup_rate_pct", 0)
        delta = hangup_rate - prev_hangup
        if abs(delta) >= 5:
            direction = "improved ✅" if delta < 0 else "worsened ⚠️"
            q.add(
                agent    = "SCRIBE",
                priority = "LOW",
                task     = (
                    f"SCRIBE NOTE: Hangup rate {direction} by {abs(delta):.1f}pp vs last week "
                    f"({prev_hangup:.0f}% → {hangup_rate:.0f}%). "
                    f"{'Keep the current opener.' if delta < 0 else 'Revert last script change or try a new hook.'}"
                ),
                metric   = f"delta={delta:+.1f}pp"
            )


# ─── Email Analysis ───────────────────────────────────────────────────────────

def analyze_email(data, q: ImprovementQueue, prev=None):
    email = data.get("email", {})
    if email.get("status") != "live":
        return

    by_subject = email.get("by_subject", {})
    by_biz     = email.get("by_business_type", {})
    dead_subj  = email.get("dead_subjects", [])
    dead_biz   = email.get("dead_biz_types", [])
    best       = email.get("best_subject")
    worst      = email.get("worst_subject")

    # Dead subject lines
    for subj in dead_subj:
        sent = by_subject[subj]["sent"]
        q.add(
            agent    = "QUILL",
            priority = "HIGH",
            task     = (
                f"QUILL TASK: Subject line '{subj}' has 0 replies after {sent} sends. "
                f"Kill it immediately — it's likely hitting spam filters or triggering delete-on-open. "
                f"Replace with a curiosity-first subject: e.g. 'Quick question about [business name]' "
                f"or '3 restaurants like yours went from 3.8★ to 4.6★ — curious how?'"
            ),
            metric   = f"sends={sent}, replies=0",
            data     = {"subject": subj, "sent": sent}
        )

    # Best vs worst comparison
    if best and worst and best["subject"] != worst["subject"]:
        ratio = best["reply_rate"] / worst["reply_rate"] if worst["reply_rate"] > 0 else float("inf")
        if ratio >= 2:
            q.add(
                agent    = "QUILL",
                priority = "MEDIUM",
                task     = (
                    f"QUILL TASK: Subject line '{best['subject']}' getting {best['reply_rate']:.1f}% reply rate. "
                    f"'{worst['subject']}' getting {worst['reply_rate']:.1f}%. "
                    f"Retire the low performer — shift all volume to the winner. "
                    f"(auto-apply.py will handle this automatically)"
                ),
                metric   = f"best={best['reply_rate']:.1f}%, worst={worst['reply_rate']:.1f}%, ratio={ratio:.1f}x",
                data     = {"best": best, "worst": worst}
            )

    # Dead business types
    for biz in dead_biz:
        sent = by_biz[biz]["sent"]
        q.add(
            agent    = "QUILL",
            priority = "MEDIUM",
            task     = (
                f"QUILL TASK: Business type '{biz}' has 0 replies after {sent} sends. "
                f"Remove from active targeting list. Either the pain isn't acute enough, "
                f"or decision-makers aren't reachable via cold email. "
                f"Consider LinkedIn or in-person for this segment."
            ),
            metric   = f"sends={sent}, replies=0",
            data     = {"biz_type": biz, "sent": sent}
        )


# ─── Stripe Analysis ──────────────────────────────────────────────────────────

def analyze_stripe(data, q: ImprovementQueue, prev=None):
    stripe = data.get("stripe", {})
    if stripe.get("status") != "live":
        return

    refunds  = stripe.get("flags", {}).get("refunds_flagged", [])
    churn    = stripe.get("flags", {}).get("churn_rate_approx", 0)
    subs     = stripe.get("active_subscribers", 0)
    mrr      = stripe.get("mrr_usd", 0)
    by_prod  = stripe.get("by_product", {})
    cancelled = stripe.get("cancelled_last_30d", 0)

    # Refunds
    for r in refunds:
        q.add(
            agent    = "GENERAL",
            priority = "HIGH",
            task     = (
                f"GENERAL: Refund request flagged — ${r['amount']:.2f} "
                f"(reason: {r.get('reason', 'unspecified')}, id: {r['id']}). "
                f"Review customer's usage data. If < 7 days old: offer onboarding call before processing. "
                f"Log pattern — if 3+ refunds cite same reason, it's a product issue."
            ),
            metric   = f"refund_id={r['id']}, amount=${r['amount']:.2f}",
            data     = r
        )

    # High churn
    if churn > 10 and cancelled >= 3:
        q.add(
            agent    = "PIXEL",
            priority = "HIGH",
            task     = (
                f"PIXEL TASK: Churn rate ~{churn:.0f}% ({cancelled} cancellations). "
                f"Review onboarding flow — high churn usually means users didn't reach 'aha moment'. "
                f"Add a progress indicator on first login, send Day-3 email with 'Here's what you're missing', "
                f"and simplify the setup to under 5 minutes."
            ),
            metric   = f"churn_rate={churn:.0f}%, cancelled={cancelled}",
            data     = {"churn": churn, "cancelled": cancelled, "active": subs}
        )

    # MRR target tracking
    target_mrr = 1500
    if mrr < target_mrr:
        gap = target_mrr - mrr
        q.add(
            agent    = "SPARK",
            priority = "MEDIUM",
            task     = (
                f"SPARK TASK: MRR ${mrr:.0f}/mo — ${gap:.0f} gap to ${target_mrr} target. "
                f"Activate a limited-time offer: 'First month free for annual plan' "
                f"or 'Lifetime deal at $149 (this week only)'. "
                f"Push via Reddit + email to existing trial users."
            ),
            metric   = f"mrr=${mrr:.0f}, target=${target_mrr}, gap=${gap:.0f}",
            data     = {"mrr": mrr, "target": target_mrr, "subs": subs}
        )

    # Before/after MRR
    if prev and prev.get("stripe", {}).get("status") == "live":
        prev_mrr = prev["stripe"].get("mrr_usd", 0)
        if prev_mrr > 0:
            growth = (mrr - prev_mrr) / prev_mrr * 100
            if growth < 0:
                q.add(
                    agent    = "SPARK",
                    priority = "MEDIUM",
                    task     = (
                        f"SPARK NOTE: MRR declined {growth:.1f}% week-over-week "
                        f"(${prev_mrr:.0f} → ${mrr:.0f}). "
                        f"Run a win-back campaign for lapsed subscribers. "
                        f"Offer 50% off first month back."
                    ),
                    metric   = f"mrr_delta={growth:.1f}%"
                )


# ─── GitHub Analysis ──────────────────────────────────────────────────────────

def analyze_github(data, q: ImprovementQueue, prev=None):
    github = data.get("github", {})

    for repo_full, repo_data in github.items():
        if repo_data.get("status") != "live":
            continue

        repo_name = repo_full.split("/")[-1]
        hot       = repo_data.get("hot_issues", [])
        ux_issues = repo_data.get("by_category", {}).get("ux", [])
        bugs      = repo_data.get("by_category", {}).get("bug", [])

        # Hot issues (3+ engagement)
        for issue in hot[:5]:
            q.add(
                agent    = "PIXEL" if issue["category"] == "ux" else "GENERAL",
                priority = "HIGH" if issue["engagement"] >= 5 else "MEDIUM",
                task     = (
                    f"{'PIXEL' if issue['category'] == 'ux' else 'GENERAL'} TASK [{repo_name}]: "
                    f"Issue #{issue['id']} has {issue['engagement']} engagement signals — "
                    f"'{issue['title']}'. "
                    f"Category: {issue['category'].upper()}. "
                    f"This is a priority fix. Review, assign, and target resolution within 7 days. "
                    f"Link: {issue['url']}"
                ),
                metric   = f"engagement={issue['engagement']}",
                data     = {"issue": issue["id"], "title": issue["title"], "url": issue["url"]}
            )

        # UX friction pattern
        if len(ux_issues) >= 3:
            titles = [i["title"] for i in ux_issues[:5]]
            q.add(
                agent    = "PIXEL",
                priority = "MEDIUM",
                task     = (
                    f"PIXEL TASK [{repo_name}]: {len(ux_issues)} open UX issues — "
                    f"pattern suggests friction in the UI. "
                    f"Top issues: {', '.join(titles[:3])}. "
                    f"Recommend: do a 30-min user walkthrough, map the friction points, "
                    f"simplify the top 2 flows first."
                ),
                metric   = f"ux_issues={len(ux_issues)}",
                data     = {"issues": ux_issues[:5]}
            )

        # Critical bugs
        for bug in bugs[:3]:
            if bug.get("comments", 0) + bug.get("reactions", 0) >= 2:
                q.add(
                    agent    = "GENERAL",
                    priority = "HIGH",
                    task     = (
                        f"GENERAL [{repo_name}]: Bug #{bug['id']} has multiple reports — "
                        f"'{bug['title']}'. "
                        f"Escalate: fix on hotfix branch, test, merge before next weekly snapshot. "
                        f"Link: {bug['url']}"
                    ),
                    metric   = f"comments={bug['comments']}, reactions={bug['reactions']}",
                    data     = bug
                )


# ─── Run ──────────────────────────────────────────────────────────────────────

def run():
    print("🧠 Running improvement engine...")

    try:
        snapshot, snap_path = load_latest_snapshot()
        print(f"  → Loaded snapshot: {snap_path}")
    except FileNotFoundError as e:
        print(f"  ✗ {e}")
        return

    prev = load_prev_snapshot()
    if prev:
        print(f"  → Loaded previous snapshot for comparison")

    q = ImprovementQueue()

    print("  → Analyzing Vapi calls...")
    analyze_vapi(snapshot, q, prev)

    print("  → Analyzing email outreach...")
    analyze_email(snapshot, q, prev)

    print("  → Analyzing Stripe...")
    analyze_stripe(snapshot, q, prev)

    print("  → Analyzing GitHub issues...")
    analyze_github(snapshot, q, prev)

    # Write improvement queue
    md = q.to_markdown(snapshot.get("date", "unknown"), prev=prev)
    with open(QUEUE_FILE, "w") as f:
        f.write(md)

    print(f"\n✅ Improvement queue written → {QUEUE_FILE}")

    # Save history entry
    history = []
    if os.path.exists(HISTORY_FILE):
        try:
            with open(HISTORY_FILE) as f:
                history = json.load(f)
        except Exception:
            history = []

    history.append({
        "date":       datetime.date.today().isoformat(),
        "snapshot":   snap_path,
        "tasks":      len(q.tasks),
        "high":       sum(1 for t in q.tasks if t["priority"] == "HIGH"),
        "medium":     sum(1 for t in q.tasks if t["priority"] == "MEDIUM"),
        "low":        sum(1 for t in q.tasks if t["priority"] == "LOW"),
        "by_agent":   {a: sum(1 for t in q.tasks if t["agent"] == a)
                       for a in ["SCRIBE","QUILL","PIXEL","SPARK","GENERAL"]},
    })

    with open(HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=2)

    # Summary print
    print(f"\n── Tasks queued: {len(q.tasks)} ──────────────────────────────")
    for task in q.tasks:
        emoji = {"HIGH":"🔴","MEDIUM":"🟡","LOW":"🟢"}.get(task["priority"], "⚪")
        print(f"  {emoji} [{task['agent']}] {task['task'][:80]}...")

    return {
        "tasks":  len(q.tasks),
        "high":   sum(1 for t in q.tasks if t["priority"] == "HIGH"),
        "queue":  QUEUE_FILE,
        "tasks_list": q.tasks,
    }


if __name__ == "__main__":
    run()
